
CREATE DATABASE mysqlforpython
USE mysqlforpython

CREATE TABLE USER(
	userid INT  NOT NULL AUTO_INCREMENT,
	username VARCHAR(100)  DEFAULT NULL,
	PRIMARY KEY (userid)
)

SELECT * FROM USER
DROP TABLE wikiurl;

CREATE TABLE wikiurl(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	urlname VARCHAR(255) NOT NULL,
	urlhref VARCHAR(1000) NOT NULL

)
